/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Vacunatorio.clases.Patologia;
import Vacunatorio.dataClass.PatologiaData;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author luciano.echevarne
 */
public class vistaPatologiaABM extends javax.swing.JInternalFrame {
    
    private PatologiaData pada;
    private Patologia p;
    /**
     * Creates new form vistaPatologiaABM
     */
    public vistaPatologiaABM(PatologiaData pada) {
        initComponents();
        this.pada=pada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jActivo = new javax.swing.JCheckBox();
        jBuscar = new javax.swing.JButton();
        jModificar = new javax.swing.JButton();
        jGuardar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patologia a.b.m.");

        jLabel2.setText("Nombre:");

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jActivo.setText("Activa si/no");
        jActivo.setEnabled(false);
        jActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActivoActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jModificar.setText("Modificar");
        jModificar.setEnabled(false);
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar)
                    .addComponent(jActivo)
                    .addComponent(jLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardar)
                    .addComponent(jModificar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActivoActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
    String nom=jTextNombre.getText();
    if(!nom.trim().isEmpty()){
        if(pada.buscarPatologiaPorNombre(nom).getNombre()==null)
            JOptionPane.showMessageDialog(this,"La patologia no se encuetra en la base, presione guardar para almacenarla");
        else{
            JOptionPane.showMessageDialog(this,"Modificar patologia");
            jGuardar.setEnabled(false);
            jModificar.setEnabled(true);
            p=pada.buscarPatologiaPorNombre(nom);
            jActivo.setEnabled(true);
            if(p.isEstado())
                jActivo.setSelected(true);
            else
                jActivo.setSelected(false);
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
    String nom=jTextNombre.getText();
    if(!nom.trim().isEmpty()){
        if(pada.buscarPatologiaPorNombre(nom).getNombre()!=null){
            JOptionPane.showMessageDialog(this,"La patologia se encuetra cargada");
            this.jLimpiarActionPerformed(evt);
        }else{
            Patologia pa=new Patologia(nom,true);
            pada.ingresarPatologia(pa);
            this.jLimpiarActionPerformed(evt);
        }
    }else{
        JOptionPane.showMessageDialog(this,"Complete campo nombre");
        this.jLimpiarActionPerformed(evt);
    }
//         TODO add your handling code here:
    }//GEN-LAST:event_jGuardarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
    jModificar.setEnabled(false);
    jTextNombre.setText(null);
    jActivo.setSelected(false);
    jActivo.setEnabled(false);
    jGuardar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
    String nom=jTextNombre.getText();
    if(!nom.trim().isEmpty()){
    Patologia pmod=new Patologia(p.getIdPatologia(),nom,jActivo.isSelected());
    pada.actualizarPatologia(pmod);
    p=null;
    JOptionPane.showMessageDialog(this,"Modificada con exito");
    this.jLimpiarActionPerformed(evt);
    }else {JOptionPane.showMessageDialog(this,"Campo nombre vacio");this.jLimpiarActionPerformed(evt);} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jModificarActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        char val=evt.getKeyChar();
        if(!Character.isLetter(val)&&val!=' '&& val != KeyEvent.VK_BACK_SPACE){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este campo solo permite LETRAS");
        }
    }//GEN-LAST:event_jTextNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jActivo;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jModificar;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
